### PR TITLE
fix #42

### LINKED ISSUE #42: console.log("%d");
```c
#include <stdio.h>
int main(void) {
    printf("%d\n");

    return 0;
}
```

### PR DESCRIPTION
**Pull request by zaoqi**
fix #42

### CODE REVIEW

**Comment by zaoqi-unsafe** [comment]
@andrei-markeev

**Comment by zaoqi** [comment]
@andrei-markeev

**Comment by andrei-markeev** [comment]
Sorry for the delay, I was on summer vacation and then some other business. I'll look into this ASAP. Are you sure that the tests are passing?

**Comment by andrei-markeev** [comment]
Hi, I just checked and the tests are failing.
To run tests, use `npm test`. To skip valgrind (it typically works only on Linux), use `npm run test-without-valgrind`.

**Comment by zaoqi** [comment]
Which test failed?

Only printf(x) (1 argument) are replaced.

**Comment by zaoqi** [comment]
```
[zaoqi@zaoqi-pc zaoqi___ts2c___patch1___readonly]$ npm run test-without-valgrind
npm ERR! missing script: test-without-valgrind
npm ERR! 
npm ERR! Did you mean this?
npm ERR!     test-no-valgrind

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/zaoqi/.npm/_logs/2019-07-24T10_17_46_610Z-debug.log
```

**Comment by andrei-markeev** [comment]
> ```
> [zaoqi@zaoqi-pc zaoqi___ts2c___patch1___readonly]$ npm run test-without-valgrind
> npm ERR! missing script: test-without-valgrind
> npm ERR! 
> npm ERR! Did you mean this?
> npm ERR!     test-no-valgrind

yep, `test-no-valgrind` is the right one, sorry for confusion

**Pull request closed without merging**
